<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6halhnk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6halhnk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6halhnk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6halhnk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6halhnk\appDevDebugProjectContainer([
    'container.build_hash' => '6halhnk',
    'container.build_id' => '0e007010',
    'container.build_time' => 1733430812,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6halhnk');
