<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxkbjtx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxkbjtx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSxkbjtx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSxkbjtx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSxkbjtx\appDevDebugProjectContainer([
    'container.build_hash' => 'Sxkbjtx',
    'container.build_id' => 'f886810e',
    'container.build_time' => 1733708259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxkbjtx');
