<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrvxtmv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrvxtmv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCrvxtmv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCrvxtmv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCrvxtmv\appDevDebugProjectContainer([
    'container.build_hash' => 'Crvxtmv',
    'container.build_id' => '7d069297',
    'container.build_time' => 1733697067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrvxtmv');
