<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrfbiyx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrfbiyx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUrfbiyx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUrfbiyx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUrfbiyx\appProdProjectContainer([
    'container.build_hash' => 'Urfbiyx',
    'container.build_id' => '04189f0b',
    'container.build_time' => 1729694057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrfbiyx');
