<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlrbfag\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlrbfag/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRlrbfag.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRlrbfag\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRlrbfag\appProdProjectContainer([
    'container.build_hash' => 'Rlrbfag',
    'container.build_id' => 'b942addd',
    'container.build_time' => 1729872936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRlrbfag');
