<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0a3rvx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0a3rvx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA0a3rvx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA0a3rvx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA0a3rvx\appProdProjectContainer([
    'container.build_hash' => 'A0a3rvx',
    'container.build_id' => 'd1a5a8a9',
    'container.build_time' => 1729687368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0a3rvx');
